# Generated by Django 2.0.8 on 2018-09-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phoneNo', models.DecimalField(decimal_places=10, max_digits=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
