# Generated by Django 2.0.8 on 2018-09-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='phoneNo',
            new_name='phnNum',
        ),
    ]
