# Generated by Django 2.0.8 on 2018-09-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_auto_20180919_1205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='Registrationf',
        ),
    ]
